version: "3"
services:
  db-postgres:
    build:
      context: .
      dockerfile: Dockerfile-db
      args:
        - PG_BD_NAME=${PG_BD_NAME}
        - PG_PASSWORD=${PG_PASSWORD}
    ports:
      - "5432:5432"
  app:   
   
    build:
     context: .
     dockerfile: Dockerfile
    ports:
      - "4000:4000" 
    volumes:
      -  ./ts-compile:/app/ts-compile
    restart: always
    links:
     - db-postgres  
     

  # nginx:
  #  image:  nginx:1.17.2-alpine
  #  container_name: nginx
  #  volumes:
  #    - ./default.conf:/etc/nginx/conf.d/default.conf
  #  links:
  #   - app

  #  ports:  
  #   - "8989:8989"